# Generated by Django 4.2.2 on 2023-06-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('country', models.CharField(choices=[('US', 'com'), ('CN', 'cn'), ('JP', 'co.jp'), ('CA', 'ca'), ('MX', 'com.mx'), ('UK', 'co.uk'), ('DE', 'de'), ('FR', 'fr'), ('IT', 'it'), ('ES', 'es'), ('NL', 'nl'), ('PL', 'pl'), ('SE', 'se'), ('AU', 'au'), ('IN', 'in'), ('SA', 'sa'), ('AE', 'ae'), ('TR', 'tr'), ('SG', 'sg'), ('BR', 'br')], max_length=6)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
